name: Ruff Lint

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - "magic/**"
      - "tests/**"

jobs:
  ruff:
    name: Ruff Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Ruff Lint
        uses: chartboost/ruff-action@v1
